/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './message.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from '@angular/common/src/localization';
import * as import6 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import7 from '@angular/forms/src/form_builder';
import * as import8 from './message.service';
import * as import9 from '@angular/core/src/di/injector';
import * as import10 from '@angular/core/src/i18n/tokens';
import * as import11 from '@angular/http/src/http';
import * as import12 from '../errors/error.service';
class MessageModuleInjector extends import0.NgModuleInjector<import1.MessageModule> {
  _CommonModule_0:import2.CommonModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _ReactiveFormsModule_3:import4.ReactiveFormsModule;
  _MessageModule_4:import1.MessageModule;
  __NgLocalization_5:import5.NgLocaleLocalization;
  __RadioControlRegistry_6:import6.RadioControlRegistry;
  __FormBuilder_7:import7.FormBuilder;
  __MessageService_8:import8.MessageService;
  constructor(parent:import9.Injector) {
    super(parent,[],[]);
  }
  get _NgLocalization_5():import5.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == (null as any))) { (this.__NgLocalization_5 = new import5.NgLocaleLocalization(this.parent.get(import10.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _RadioControlRegistry_6():import6.RadioControlRegistry {
    if ((this.__RadioControlRegistry_6 == (null as any))) { (this.__RadioControlRegistry_6 = new import6.RadioControlRegistry()); }
    return this.__RadioControlRegistry_6;
  }
  get _FormBuilder_7():import7.FormBuilder {
    if ((this.__FormBuilder_7 == (null as any))) { (this.__FormBuilder_7 = new import7.FormBuilder()); }
    return this.__FormBuilder_7;
  }
  get _MessageService_8():import8.MessageService {
    if ((this.__MessageService_8 == (null as any))) { (this.__MessageService_8 = new import8.MessageService(this.parent.get(import11.Http),this.parent.get(import12.ErrorService))); }
    return this.__MessageService_8;
  }
  createInternal():import1.MessageModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._ReactiveFormsModule_3 = new import4.ReactiveFormsModule();
    this._MessageModule_4 = new import1.MessageModule();
    return this._MessageModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import4.ReactiveFormsModule)) { return this._ReactiveFormsModule_3; }
    if ((token === import1.MessageModule)) { return this._MessageModule_4; }
    if ((token === import5.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import6.RadioControlRegistry)) { return this._RadioControlRegistry_6; }
    if ((token === import7.FormBuilder)) { return this._FormBuilder_7; }
    if ((token === import8.MessageService)) { return this._MessageService_8; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const MessageModuleNgFactory:import0.NgModuleFactory<import1.MessageModule> = new import0.NgModuleFactory(MessageModuleInjector,import1.MessageModule);