/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './message-list.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './message.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '@angular/common/src/directives/ng_for';
import * as import13 from '@angular/core/src/linker/template_ref';
import * as import14 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import15 from './message.component';
import * as import16 from './message-edit.component';
import * as import17 from './message.component.ngfactory';
import * as import18 from './message-edit.component.ngfactory';
import * as import19 from '@angular/core/src/security';
var renderType_MessageListComponent_Host:import0.RenderComponentType = (null as any);
class _View_MessageListComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _MessageListComponent_0_4:import3.MessageListComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MessageListComponent_Host0,renderType_MessageListComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-message-list',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MessageListComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MessageListComponent_0_4 = new import3.MessageListComponent(this.parentInjector.get(import8.MessageService));
    this._appEl_0.initComponent(this._MessageListComponent_0_4,[],compView_0);
    compView_0.create(this._MessageListComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.MessageListComponent) && (0 === requestNodeIndex))) { return this._MessageListComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._MessageListComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MessageListComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_MessageListComponent_Host === (null as any))) { (renderType_MessageListComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_MessageListComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const MessageListComponentNgFactory:import10.ComponentFactory<import3.MessageListComponent> = new import10.ComponentFactory<import3.MessageListComponent>('app-message-list',viewFactory_MessageListComponent_Host0,import3.MessageListComponent);
const styles_MessageListComponent:any[] = [];
var renderType_MessageListComponent:import0.RenderComponentType = (null as any);
class _View_MessageListComponent0 extends import1.AppView<import3.MessageListComponent> {
  _viewQuery_edit_0:import11.QueryList<any>;
  _anchor_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TemplateRef_0_5:any;
  _NgFor_0_6:import12.NgFor;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MessageListComponent0,renderType_MessageListComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_edit_0 = new import11.QueryList<any>();
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import13.TemplateRef_(this._appEl_0,viewFactory_MessageListComponent1);
    this._NgFor_0_6 = new import12.NgFor(this._appEl_0.vcRef,this._TemplateRef_0_5,this.parentInjector.get(import14.IterableDiffers),this.ref);
    this._expr_0 = import7.UNINITIALIZED;
    this.init([],[this._anchor_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import12.NgFor) && (0 === requestNodeIndex))) { return this._NgFor_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.context.messages;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_0_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_0_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_0_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if (this._viewQuery_edit_0.dirty) {
        this._viewQuery_edit_0.reset([this._appEl_0.mapNestedViews(_View_MessageListComponent1,(nestedView:_View_MessageListComponent1):any => {
          return [nestedView._MessageEditComponent_6_4];
      })]);
      this.context.editComponent = this._viewQuery_edit_0.first;
    } }
  }
}
export function viewFactory_MessageListComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.MessageListComponent> {
  if ((renderType_MessageListComponent === (null as any))) { (renderType_MessageListComponent = viewUtils.createRenderComponentType('C:/Users/Sebastian/Desktop/DEV/udemytutorial/03 MongoDB/assets/app/messages/message-list.component.html',0,import9.ViewEncapsulation.None,styles_MessageListComponent,{})); }
  return new _View_MessageListComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_MessageListComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _MessageComponent_4_4:import15.MessageComponent;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _MessageEditComponent_6_4:import16.MessageEditComponent;
  _text_7:any;
  _text_8:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MessageListComponent1,renderType_MessageListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-md-8 col-md-offset-2');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'app-message',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import17.viewFactory_MessageComponent0(this.viewUtils,this.injector(4),this._appEl_4);
    this._MessageComponent_4_4 = new import15.MessageComponent(this.parentInjector.get(import8.MessageService));
    this._appEl_4.initComponent(this._MessageComponent_4_4,[],compView_4);
    compView_4.create(this._MessageComponent_4_4,[],(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'app-message-edit',(null as any));
    this._appEl_6 = new import2.AppElement(6,2,this,this._el_6);
    var compView_6:any = import18.viewFactory_MessageEditComponent0(this.viewUtils,this.injector(6),this._appEl_6);
    this._MessageEditComponent_6_4 = new import16.MessageEditComponent(this.parentInjector.get(import8.MessageService));
    this._appEl_6.initComponent(this._MessageEditComponent_6_4,[],compView_6);
    compView_6.create(this._MessageEditComponent_6_4,[],(null as any));
    this._text_7 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_4,'editClicked',this.eventHandler(this._handle_editClicked_4_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    const subscription_0:any = this._MessageComponent_4_4.editClicked.subscribe(this.eventHandler(this._handle_editClicked_4_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_6,'submitClicked',this.eventHandler(this._handle_submitClicked_6_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    const subscription_1:any = this._MessageEditComponent_6_4.submitClicked.subscribe(this.eventHandler(this._handle_submitClicked_6_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.MessageComponent) && (4 === requestNodeIndex))) { return this._MessageComponent_4_4; }
    if (((token === import16.MessageEditComponent) && (6 === requestNodeIndex))) { return this._MessageEditComponent_6_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._MessageComponent_4_4.message = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._MessageEditComponent_6_4.message = currVal_4;
      this._expr_4 = currVal_4;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._MessageEditComponent_6_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this.parent.context.displayState[this.context.index];
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementStyle(this._el_6,'display',((this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_3) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_3).toString()));
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_MessageListComponent0>this.parent)._viewQuery_edit_0.setDirty();
  }
  private _handle_editClicked_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onEditClicked(this.context.index)) !== false);
    return (true && pd_0);
  }
  private _handle_submitClicked_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onEditClicked(this.context.index)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_MessageListComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MessageListComponent1(viewUtils,parentInjector,declarationEl);
}